### ISSUE TITLE
wallet.advcash.com being blocked

### ISSUE THREAD

**Issue by downloadkct** [nextdns/metadata#1060]
Hi, wallet.advcash.com is being blocked and this is a trusted page

**Comment by hagezi** [comment]
Blocked by @anudeepND (Blacklist) @bamojr (Pro) @velesila (yHosts) and @privacy-protection-tools

Regards,
Gerd - https://github.com/hagezi/dns-blocklists

**Comment by downloadkct** [comment]
![image](https://user-images.githubusercontent.com/24975841/188398881-b3a7aa94-e29d-445d-8418-590494b3b605.png)

Im not using any of these :(

**Comment by crssi** [comment]
You are using NextDNS's one, which is a sum of several lists and some of those are constant culprit.

Use `oisd` and `1Hosts (Lite)` only... I am sure those will cover all your needs and you will be happy as never before. 😄 

For more details you can also check in my profile, its not been updated for a long time and that is not because its abandoned, but because it just does not need any update yet.

Cheers

**Comment by VeleSila** [comment]
Even though it does not provide servies in U.S. I just skim through advcash.com and it seems to a valid E-wallet website. I'm out of town now. I'll look into it in Nov/Dec when I'm home.

**Comment by romaincointepas** [comment]
Fixed
