### ISSUE TITLE
Remove phishing-domains-ACTIVE.txt

### ISSUE THREAD

**Issue by beerisgood** [nextdns/metadata#127]
The "https://raw.githubusercontent.com/mitchellkrogza/Phishing.Database/master/phishing-domains-ACTIVE.txt" filterlist have a lot of false positives and even after many day's they don't get removed.

I wouldn't call that reliable.
Examples:
https://github.com/mitchellkrogza/Phishing.Database/issues/52,
https://github.com/mitchellkrogza/Phishing.Database/issues/26,
https://github.com/mitchellkrogza/Phishing.Database/issues/24,
https://github.com/mitchellkrogza/Phishing.Database/issues/61,
https://github.com/mitchellkrogza/Phishing.Database/issues/62

**Comment by scafroglia93** [comment]
+1

**Comment by romaincointepas** [comment]
Removed, thanks.

**Comment by funilrys** [comment]
I can't talk for those who are still open (cc @mitchellkrogza)

But the bug in the whitelisting tool is now fixed.

**Comment by mitchellkrogza** [comment]
The whitelisting tool had failed, it has been fixed now and all whitelisting entries are now removed. Since apologies for this, future builds will fail if the whitelisting tool ever fails.

**Comment by romaincointepas** [comment]
@mitchellkrogza Why do domains like `gitlab.com` and `cdn.discordapp.com` make it into the list pre-whitelisting? Is it because Phishing.Database is feeding from URL-based phishing lists?

**Comment by mitchellkrogza** [comment]
Hi @romaincointepas  The data comes in from various feeds all URL based I separate URL and domain lists and whitelist them differently. So for instance docs.google.com links which have been used and are still extensively used in Phishing attacks and sharing of Phishkits are anti-whitelisted for the lists of URLS but then in the domains list we whitelist those root domains so in the domains lists dosc.google.com does not appear. I now have an `ALL *.google.com` rule but not necessarily a `ALL *.gitlab.com` rule as we will whitelist gitlab.com itself but not potential repo's that have been or may be used in future for any Phishing activity. Hope this makes sense. 

We've never had issues with whitelisting but some changes in the tool a little time ago were not detected by me as the script had a missing `set -e` my fault which did not cause TravisCI to fail the builds otherwise we would have not this sooner.

**Comment by mitchellkrogza** [comment]
@romaincointepas if you check this file - https://github.com/mitchellkrogza/Phishing.Database/blob/master/phishing-links-ACTIVE.txt you will see some gitlab.io repo's that were once used for phishing. I do not find any gitlab.com links in there though so I am not sure how that every entered any of these lists in the first place but they are both now properly whitelisted in the domains lists.

**Comment by romaincointepas** [comment]
@mitchellkrogza got it, re-added. And thanks for taking the time to explain!

On a side note, we would really like to have not-so-opinionated experts like yourself hanging around this repo to shine some lights on some security-related debates (or blocklists in general).
