### ISSUE TITLE
eonline.com and justjared.com marked as porn

### ISSUE THREAD

**Issue by ammnt** [nextdns/metadata#159]
Hello,

eonline.com and justjared.com marked as porn, but this is actually celebrity news portals. Please, take a look.

Thank you.

Cheers!

**Comment by ammnt** [comment]
thehollywoodgossip.com is blocked as porn site too.

**Comment by romaincointepas** [comment]
They are all blocked by https://github.com/Clefspeare13/pornhosts.

`thehollywoodgossip.com` is also blocked by https://github.com/mhxion/pornaway.

Can you create an issue there? Always better to fix upstream.

Maybe @scafroglia93 can assist.

**Comment by scafroglia93** [comment]
https://github.com/mhxion/pornaway-> latest update was made Sep 4, 2018 (it's not mantained)

**Comment by scafroglia93** [comment]
issue was resolved by upstream

**Comment by lyrad87** [comment]
@romaincointepas this can be closed, all three mentioned websites have been resolved upstream.

**Comment by spirillen** [comment]
This one can be closed as those domains no longer reside in the list, next time please post this upstream at https://mypdns.org/my-privacy-dns/porn-records as this is only because of https://github.com/nextdns/metadata/issues/834 I ever found this information.

- thehollywoodgossip.com https://mypdns.org/my-privacy-dns/porn-records/-/commit/85930795c00755e5319bbf694d46a73aa78137fe
- eonline.com https://mypdns.org/my-privacy-dns/porn-records/-/commit/98679cb4909f3050299b9a79559e5bac0da49a5f
- justjared.com https://mypdns.org/my-privacy-dns/porn-records/-/commit/175a0a39f0698ac2be04913f799e3e0c9effdbd1

**Comment by romaincointepas** [comment]
Fixed (we have moved to our internal Porn AI).
