### ISSUE TITLE
Facebook block issue

### ISSUE THREAD

**Issue by specter78** [nextdns/metadata#210]
It is not blocking `facebook.net`.

**Comment by lyrad87** [comment]
Can you please double-check if it's `facebook.net` and not `fbcdn.net`?
And how do you have Facebook blocked exactly? Are you using the 'No Facebook' blocklist or the option under 'Parental Control'?

If it's the latter, it should be blocked since it was added with one of the recent pull requests -> #200 . Maybe it will be fixed with the new pull request #205 which will add the `fbcdn.net` domain.

**Comment by specter78** [comment]
> Can you please double-check if it's `facebook.net` and not `fbcdn.net`?

Yes, it is `facebook.net`.

> And how do you have Facebook blocked exactly? Are you using the 'No Facebook' blocklist or the option under 'Parental Control'?

Parental Control

> If it's the latter, it should be blocked since it was added with one of the recent pull requests -> #200 . Maybe it will be fixed with the new pull request #205 which will add the `fbcdn.net` domain.

That's why it's surprising because it should be blocked which isn't happening.

**Comment by lyrad87** [comment]
Surprising indeed. 🤔Thanks for the follow-up though. @romaincointepas maybe you have an idea what is not working correctly?

**Comment by romaincointepas** [comment]
Fixed, sorry about that, for some reason the services weren't auto-updating from github.
