### ISSUE TITLE
Create ability to add pre-made whitelists

### ISSUE THREAD

**Issue by momenabdelkarim** [nextdns/metadata#216]
Feature request due to website functionality breaking:

Under “privacy,” we can select from many popular blocklists and they’re automatically updated. It would be really nice to be able to do the same but for whitelists (such as [anudeepND’s whitelist](https://github.com/anudeepND/whitelist)).

Being able to subscribe to these whitelists is important because even the most refined blocklists, such as NextDNS’s recommend blocklist, break functionality such as YouTube watch history, Plex features, and more (anudeepND’s list solves for these issues).

I understand creating the ability to select from multiple premade whitelists that automatically update might take quite a bit of work. In the meantime, it would be nice to be able to upload a .txt file to be able to bulk add the whitelisted domains (and remove them in bulk).

**Comment by romaincointepas** [comment]
We added *Allow affiliate & tracking links*, which covers the majority of the use cases.

For the rest, this can be easily fixed by whitelisting (those are highly opinionated anyway, from our experience people don't want to whitelist the same things), or by convincing the owners of your favorite blocklist.
