### ISSUE TITLE
Additional domain in Facebook service

### ISSUE THREAD

**Issue by jlapthorn** [nextdns/metadata#27]
Can you add "fbcdn.net" to facebook  service

**Comment by romaincointepas** [comment]
This could potentially break other Facebook-owned services like Instagram and Messenger, we will investigate.

**Comment by gracjankn** [comment]
@romaincointepas Maybe add the ability to block **everything** Facebook related in one shot? I'd highly appreciate that, because I'm 100% off all Facebook services including Messenger, Instagram and Whatsapp.

A few example lists for that (they also block the "fbcdn.net" domain):
https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/facebook/all
https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt
https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt
https://gitlab.com/CHEF-KOCH/cks-filterlist/blob/master/Anti-Corp/filters/facebook.txt

They are mentioned on [pihole-google](https://github.com/nickspaargaren/pihole-google) that's available in NextDNS.

**Comment by gracjankn** [comment]
> @romaincointepas Maybe add the ability to block **everything** Facebook related in **one shot**? I'd highly appreciate that, because I'm 100% off **all Facebook services** including Messenger, Instagram and Whatsapp.
> 
> A few **example lists** for that (they also block the "**fbcdn.net**" domain):
> https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/facebook/all
> https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt
> https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt
> https://gitlab.com/CHEF-KOCH/cks-filterlist/blob/master/Anti-Corp/filters/facebook.txt
> 
> They are **mentioned** on [pihole-google](https://github.com/nickspaargaren/pihole-google) that's **available in NextDNS**.

I made a pull request for that, adding Anudeep's Facebook blocklist: https://github.com/nextdns/lists/pull/56

**Comment by s-crypt** [comment]
@romaincointepas I can confirm that fbcdn.com blocks instagram services, unsure about messenger and whatsapp.

**Comment by romaincointepas** [comment]
Closing, moving the discussion to https://github.com/nextdns/metadata/pull/56.
