### ISSUE TITLE
Ip block list

### ISSUE THREAD

**Issue by aelisya** [nextdns/metadata#305]
IS there a way to add the Energized list of BAD ip ?
https://block.energized.pro/extensions/ips/formats/list.txt

and if a domain name respond one of these ip, the response is replaced by 0.0.0.0 ?

Like that, even if a malicious IP have a domain name, that isn't in the "normal" blocklist, it will be blocked too.

**Comment by Voltairine-de-Cleyre** [comment]
IP blocking would be wonderful. I'd look into alternatives to Energized's list, however. https://isc.sans.edu/ has good information; their data feed section shows names of respected sources. Here on GitHub is https://github.com/firehol/blocklist-ipsets - the level one list is good, level two if you don't mind a false positive now and then. ✌🏼

**Comment by scafroglia93** [comment]
I don't think it's possible

**Comment by beerisgood** [comment]
Like scafroglia93 already said that's not possible nor how DNS works.

**Comment by aelisya** [comment]
how, since it's impossible do you know a way to do it client side on windows/linux/android ?

Thanks for help (after the next answer i will close the issue)

**Comment by Voltairine-de-Cleyre** [comment]
There are IPs present in many lists used at the DNS level, especially hosts files that when used at the DNS level instead of in the traditional way, function fine. AdGuard's applications handle IPs within filter lists very well at the DNS level including DoT, DoH & DNSCrypt v2 (and unencrypted DNS as well). Saying it's not possible simply isn't true.

@aelisya , for linux check out the Firehol package itself - it should be present in whichever distro you use. Another option is to run AdGuard Home - https://github.com/AdguardTeam/AdGuardHome - which you can then use within your router or use as a LAN DNS server or properly secure & open up as a WAN server which you can then use outside your LAN / home / business / etc. & share with close friends / family if you so choose. Finally, there's https://suricata-ids.org/features/all-features/ which is a fantastic solution for Linux, BSD, Mac & Windows. AdGuard's Windows "normal" software does cost money, but it functions well, though AdGuard Home is free & can be run off of a Raspberry Pie or in a Docker container (I know of no direct Window's support). When it was first released, it functioned but didn't function well; it has since matured, however & today does function well, and is easy to build from source if one so chooses. It is a DNS-level solution and just as hosts files with IPs in them { as @aelisya initially inquired such as `0.0.0.0 181.129.104.139` ( **Caution**: that's an actual currently online botnet IP so **avoid it**. ) } and IP lists that are used directly as a filter subscription for use within, e.g. AdGuard or AdGuard home, both if which operate at the network/DNS level) or modified for use with, e.g. Sucrita - all function gracefully using IPs within black lists or using pure  IP block lists.

**Comment by romaincointepas** [comment]
We feel supporting IP blocklists is not really worth it:

1. In the age of VPS, this results in a ton of false positives.

2. Most of those IPs are usually accessed directly and are not part of a DNS answer, so they won't be caught.

Regarding adguard, they may support those lists but do they actually block domains answering those IPs?

**Comment by Voltairine-de-Cleyre** [comment]
Yes, they actually do. I can put in, e.g. the IP of the DNS server for a specific facebook subdomain & if will block the subdomain itself in the answer it returns.

**Comment by rs** [comment]
The question is not if it does technically work but if blocking by IP provides any value. Most services are multi-homed with dynamic IP sets. Blocking IPs based on DNS response will most likely create a lot of false positive because of the multi-homing and might also miss a lot of IPs at the same time.

What @romaincointepas is asking is if you have a use-case where DNS based IP blocking would solve an actual issue that can't be solved with regular domain blocking. So far we haven't found one.

**Comment by aelisya** [comment]
the only one who came in my mind, it's for mass blocking of GAFAM, since they own block of IP/IPV6, it's more efficient than blocking domain (since the create them automatically(the list isn't easy to maintain)).

**Comment by rs** [comment]
You will also block google cloud services which can give unexpected results.

**Comment by aelisya** [comment]
yes it was an exemple ^^, i was more thinking for the future ipv6 (in ipv4 worl it isn't woth the work), but since ipv6, have more ip, the ipv6 block list can have an interest in the future.
