### ISSUE TITLE
Remove NSABlocklist from the blocklist

### ISSUE THREAD

**Issue by crssi** [nextdns/metadata#340]
Please, consider to remove outdated list NSABlocklist.
Also this list is not to be trusted due to author plagiarism history.

Cheers

**Comment by beerisgood** [comment]
Everything from "Chef-Koch" is suspicious as he just copy work from other's and remove all copyright etc.

See https://github.com/ghacksuserjs/ghacks-user.js/issues/323

**Comment by quantumpacket** [comment]
This is why I also don't use the Spotify blocklist. Anything by Chef-Koch can't be trusted. If he is willing to steal others work he is willing to be malicious in other ways. The last thing I want is for my device security updates to silently stop working because someone added their DNS entries to a blocklist. We should always use trusted upstream original lists.

**Comment by crssi** [comment]
Sure, the spotify was the next one. CK is just not to be trusted.

**Comment by romaincointepas** [comment]
This blocklist is used by many, is quite unique and is based on valid source (at least at the time, not sure now).

The general idea behind letting users use third-party blocklists is that we include them based on popularity while trying to not be opinionated about it and not pass judgment. That's also why we never alter them, even when they include obvious false positives.

Regarding the plagiarim, if anyone can link to the original/copied version we will swap (couldn't find it).

**Comment by beerisgood** [comment]
His GitHub (and GitLab) account is banned for e.g. reasons posted in my link

**Comment by Voltairine-de-Cleyre** [comment]
> The general idea behind letting users use third-party blocklists is that we include them based on popularity while trying to not be opinionated about it and not pass judgment. That's also why we never alter them, even when they include obvious false positives.

@romaincointepas  I get that. But @beerisgood is correct in this matter. Even if CK didn't plagerise that NSA Blocklist (he actually didn't), he was banned from GitHub for plagerising @crazy-max's WindowsSpyBlocker. This issue is dead, regardless. But as for using blocklists based on popularity, one must ask oneself "when was this popular?" *as well as* "is this popoluar?". Finally, you may not be concerned with false positives, but using lists as out of date such as the NSA blocklist will essentially result in one of two scenarios. One is that the spectrum goes from false positives to false negatives, which is at least insecure & at most destructive for (x)device using NextDNS. The second possibility is that the list in question doesn't do a thing since the same threats no longer exist. That applies to most lists.
