### ISSUE TITLE
4shared, false positive

### ISSUE THREAD

**Issue by sherifkhalifa** [nextdns/metadata#349]
Hello there,
4shared.com is blocked, it's just a file hosting and sharing site.
Thanks

**Comment by crssi** [comment]
NOTE: I am not part of NextDNS and this response is not official... its just how I deal with those nasties. 😉 

`www.4shared.com` is blocked by https://winhelp2002.mvps.org/hosts.txt, which is part of StevenBlack list, which is also part of nextdns list.

Find Contact link at https://winhelp2002.mvps.org/ and report... in the mean time you can use Allowlist.

Suspicious on 4shared is that almost every image has its own subdomain, which could be for fingerprinting purpose.

Cheers

**Comment by sherifkhalifa** [comment]
> NOTE: I am not part of NextDNS and this response is not official... its just how I deal with those nasties. 😉
> 
> `www.4shared.com` is blocked by https://winhelp2002.mvps.org/hosts.txt, which is part of StevenBlack list, which is also part of nextdns list.
> 
> Find Contact link at https://winhelp2002.mvps.org/ and report... in the mean time you can use Allowlist.
> 
> Suspicious on 4shared is that almost every image has its own subdomain, which could be for fingerprinting purpose.
> 
> Cheers

Thank you,
How can I find the list that blocks a specific site in the future if I had this problem again?

**Comment by crssi** [comment]
In the log you find a blocked domain and hover with mouse on red circle on the right side.
A balloon popup will show telling you the blocking reason.

With that info (let say the reason is the blocklist), you can go here https://github.com/nextdns/metadata/tree/master/privacy/blocklists , open the list and you will see more info where to go to.

Some of those lists, like StevenBlack, consists some other lists. You need to find out which one is responsible and contact the maintainer for help.

Sometimes you wont accomplish desired results... in that case just use Allowlist or Denylist accordingly.

NOTE: I am not native English speaker and I am sure I fail to efficiently express myself 😉, but I hope you understood the instructions.

Cheers

**Comment by romaincointepas** [comment]
Closing, thanks @crssi for assisting.
