### ISSUE TITLE
add to category of porn

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/metadata#356]
![image](https://user-images.githubusercontent.com/19517680/89128356-5da4b800-d51f-11ea-800a-336761efbb22.png)

xnxx.wareporn.com
mojoporntube.com
ipornerhd.net

**Comment by lyrad87** [comment]
Same comment as for #360 

NextDNS is using these four lists for the porn category: https://github.com/nextdns/metadata/blob/master/parentalcontrol/categories/porn.json

I'd suggest creating the very same issue in one of those four repositories so that they can include them. I don't think NextDNS will manually add those entries.

**Comment by romaincointepas** [comment]
Could you suggest those at https://dsi.ut-capitole.fr/cgi-bin/squidguard_modify.cgi? This is one of the list we source for porn and they are responsive.

@lyrad87 feel free to suggest this next time for porn additions.
