### ISSUE TITLE
t.umblr.com blocked by typosquatting

### ISSUE THREAD

**Issue by jrhz** [nextdns/metadata#358]
t.umblr.com is blocked, but it's just their redirect service. umblr.com is owned and run by tumblr.com.

**Comment by romaincointepas** [comment]
Fixed with https://github.com/nextdns/metadata/commit/c4cef2119e587dd986d25c9f69a673d42aafb98f.

The way we approach typosquatting is:
- if the domain is owned by the company but only there to catch typos (usually it ends up redirecting to the original domain), we block it.
- if the domain is owned and actively used by the company, we don't block it.
