### ISSUE TITLE
Category of Sex isn't being blocked & list of sites aren't being blocked

### ISSUE THREAD

**Issue by cbacit** [nextdns/metadata#360]
Right now I have had to manually add over 300 + sites because the category "sex" isn't being blocked.  Please add additional category's.

![Monday, August 3, 2020_07h58m25s_004_Chrome Legacy Window](https://user-images.githubusercontent.com/47609657/89185067-3ec61600-d55f-11ea-9501-63540ba97a1d.png)

Attached is sites that are not being blocked by "Adult" category and they are sex sites please validate each and every one and tell me why the adult content on these sites are not being blocked.

**Comment by lyrad87** [comment]
NextDNS is using these four lists for the porn category: https://github.com/nextdns/metadata/blob/master/parentalcontrol/categories/porn.json

The domains you have manually blocked don't seem to be included in those lists so I'd suggest creating the very same issue in one of those four repositories so that they can include them. I don't think NextDNS will manually add those entries.

**Comment by 3xploiton3** [comment]
> 
> 
> NextDNS is using these four lists for the porn category: https://github.com/nextdns/metadata/blob/master/parentalcontrol/categories/porn.json
> 
> The domains you have manually blocked don't seem to be included in those lists so I'd suggest creating the very same issue in one of those four repositories so that they can include them. I don't think NextDNS will manually add those entries.

thx for advice,

nextdns team should be more responsive to client feedback

**Comment by romaincointepas** [comment]
Could you suggest those at https://dsi.ut-capitole.fr/cgi-bin/squidguard_modify.cgi? It's one of the list we source for porn and they are pretty responsive.
