### ISSUE TITLE
False positive: answers.unity3d.com

### ISSUE THREAD

**Issue by virgiliu** [nextdns/metadata#373]
![image](https://user-images.githubusercontent.com/426097/90315461-0984d500-df1c-11ea-82eb-e15fc4ff3748.png)

This is a game development forum, it shouldn't be blocked.

I believe it's blocked by https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts, which has `0.0.0.0 answerhub.com`

**Comment by krystian3w** [comment]
so need report here: https://github.com/StevenBlack/hosts - @nextdns no copy report into `StevenBlack` (seemingly stupid, but the truth)

**Comment by crssi** [comment]
Nah. Is even worse. `StevenBlack` is also more or less the collection of other lists, see https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant.
You need then to sweep over those to find out that the last one in the chain is `Dan Pollock – someonewhocares` where you should post an issue.

Good luck with that, since Dan is not responsive over email and on the Tweeter his last post was on Oct 4, 2019... I hope he is OK.

IMHO, the NextDNS will have to find some true professional sources.

Cheers

**Comment by krystian3w** [comment]
Someone update file 9 days ago.

Maybe `StevenBlack/hosts` have script to delete line with python / linux shell / CI machine.

**Comment by romaincointepas** [comment]
Does seem to be blocked anymore, tell me if that's not the case for you.
