### ISSUE TITLE
Top3000 most prevalent tracking and advertising networks

### ISSUE THREAD

**Issue by Kees1958** [nextdns/metadata#382]
Hi, would this be the correct JSON format for Kees1958 Most used trackers in Europe and North America?

I excluded facebook.com and facebook.net, because they need the ABP-format rules third-party and domain exclusion. For host file usage (block first and third party) this would cause unwanted blocks.

______________________________________________________________________
{
  "name": "Kees1958 Most used tracking and advertising networks in EU and North America",
  "website": "https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist",
  "description": "Most prevalent advertising and tracking networks in Western Europe and North American websites based on annual web-tech surveys.",
  "source": {
    "url": "https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/EU_US_most_common_trackers",
    "format": "abp"
  },
  "exclusions": [
"facebook.com",
"facebook.net"
  ]
}

**Comment by crssi** [comment]
There is a line `||ebay.com$third-party` which is bad.
Someone could browse to `ebay.de` or `ebay.co.uk` or any other TLD and the site will break, since all of them are calling to main URL... that is `ebay.com`.

Also, I haven't noticed that this list would kick a lot, but cannot speak of, since we really really need a possibility to export logs for further analysis.

**Comment by Kees1958** [comment]
OK removed that one
