### ISSUE TITLE
go.opendoors.nl blocked by 'blocklist:nextdns-recommended'

### ISSUE THREAD

**Issue by theovds** [nextdns/metadata#397]
Not able to register for event.
Please remove. Many thanks!
![image](https://user-images.githubusercontent.com/23518492/92937316-7a4fdc00-f44b-11ea-8a76-4e99deca2e57.png)

**Comment by scafroglia93** [comment]
NextDNS is not at fault, you have to report everything to the maintainer of the list so that he can fix the problem

**Comment by theovds** [comment]
Thanks! How do I figure out which repo is causing this false positive?

**Comment by scafroglia93** [comment]
> I'd suggest adding the domain to the Allowlist for the time being. And I would create an issue in Steven Black's repo so that he can fix it upstream.

**Comment by theovds** [comment]
Sure, I did read that comment. However, how do I (in the future) figure out from within the NextDNS website, which repo is causing this? In the logs I only see that the website is blocked by 'blocklist:nextdns-recommended'.

**Comment by crssi** [comment]
From you screenshot you see that the culprit is `pardot.com` or `pi.pardot.com` blocked by `nextdns-recommended`
Visit https://github.com/nextdns/metadata/tree/master/privacy/blocklists where you can find https://github.com/nextdns/metadata/blob/master/privacy/blocklists/nextdns-recommended.json and there you will find links to sources out of which `nextdns-recommended` is build of.

Sweeping over those you will see that https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts has a listing of `pi.pardot.com`.

On upper link at the start you will find a link to StevenBlack project site: https://github.com/StevenBlack/hosts
Visiting it you will find that StevenBlack list also is build of dozen external sources and on of his.

You can decide to submit an issue to Steven, but mught be better to submit it ti its upstream.

Sweeping over you will find that `pi.pardot.com` is listed on https://winhelp2002.mvps.org/hosts.txt and on https://pgl.yoyo.org/adservers/serverlist.php

So to get rid of, the both sources should make a de-listing.
Good luck with that, since exactly those are not responding well, including Seven itself.

Cheers

**Comment by oskapt** [comment]
If NextDNS is building its lists from upstream list sources with invalid information who are then unresponsive, how much value does NextDNS's service truly have? In particular, you've labeled this as "nextdns-recommended" but then you don't accept responsibility for its content. Why, then, are you recommending it? Why not aggregate it and then filter out erroneous entries for your users? That's like....a Python script with some regular expressions. 

In the case of #405, you'll have a hard time arguing that it's appropriate to block the Center for Internet Security, so saying, "oh hey good luck trying to get it removed" just translates, in my mind, to "oh hey, good luck getting me to renew my account when it comes up in a year."

You're supposed to be making things _better_, not sharing what's craptastic about using these lists directly.

**Comment by ignoramous** [comment]
@crssi NextDNS does maintain its own exclusion list separate from upstream? @oskapt  if you have strong justification to have the domain excluded from the list, consider creating a pull-request which adds the domain in-question [to this list](https://github.com/nextdns/metadata/blob/master/privacy/blocklists/nextdns-recommended.json#L20-L34) to see if @romaincointepas agrees with you.  [You can edit the list from right within your browser](https://github.com/nextdns/metadata/edit/master/privacy/blocklists/nextdns-recommended.json#L20).

**Comment by crssi** [comment]
@ignoramous 

> NextDNS does maintain its own exclusion list separate from upstream?

I am not NextDNS team member and thus I cannot answer. I see the same as you here https://github.com/nextdns/metadata/blob/master/privacy/blocklists/nextdns-recommended.json

**Comment by romaincointepas** [comment]
Doesn't seem to be blocked by our recommended list anymore, closing.

**Comment by obeho** [comment]
> 
> 
> Sure, I did read that comment. However, how do I (in the future) figure out from within the NextDNS website, which repo is causing this? In the logs I only see that the website is blocked by 'blocklist:nextdns-recommended'.

I found a tool that also serves this exact purpose `https://blocklist-tools.developerdan.com/entries/search` @theovds

**Comment by crssi** [comment]
@obeho 
That is great.
It will be helpful in the future, but it is missing some lists ATM... for example this one `https://pgl.yoyo.org/adservers/serverlist.php`.

**Comment by obeho** [comment]
Actually, it is included. See `Peter Lowe: Adservers` Unfortunately 1Hosts list is not there. 

You can contact the database owner `https://www.reddit.com/user/lightswitch05`, he is thinking of reducing some low quality lists from the database as its too big it seems. 

> It will be helpful in the future

I'm actively using this database query function to report the false positives to all the lists.
