### ISSUE TITLE
[Question] ipv6 & ipv4 range for firewall

### ISSUE THREAD

**Issue by aelisya** [nextdns/metadata#401]
Hello i would like to block all possible way to bypass my nextdns, so i want to block all your ip range, and only allow the ip of my profile (in installation) since my network work in ipv6 all ipv4 will be blocked.

So my question is, what's your range + Cidr ?

Thanks
nb: this information is welcome in faq ^^

**Comment by quantumpacket** [comment]
From what I can determine the range is 45.90.28.0 - 45.90.31.255, but that could be just for the US servers.

**Comment by aelisya** [comment]
> From what I can determine the range is 45.90.28.0 - 45.90.31.255, but that could be just for the US servers.

Thanks for the response, but i ask to the admin directly because like i said, i don't want to miss or take an inoccent ip by accident ^^

**Comment by quantumpacket** [comment]
@aelisya why don't you just query the RIPE database? I got the above info from there.

NextDNS: https://apps.db.ripe.net/db-web-ui/lookup?source=ripe&key=ORG-NI87-RIPE&type=organisation
IPv6: https://apps.db.ripe.net/db-web-ui/lookup?source=RIPE&type=inet6num&key=2a07:a8c0::%2F29
IPv4: https://apps.db.ripe.net/db-web-ui/lookup?source=RIPE&type=inetnum&key=45.90.28.0%20-%2045.90.31.255

> so i want to block all your ip range, and only allow the ip of my profile (in installation) since my network work in ipv6 all ipv4 will be blocked.

Why don't you just block all DNS traffic, and only allow DNS traffic to your IP for your profile. That way you are blocking by protocol and not merely by IP. Otherwise, any IP that is not being blocked can still be used for DNS on the network.

**Comment by aelisya** [comment]
if you block 53 and 853, dnscrypt still work, if you block by dns domain dnscrypt still work, and if you block the download adresse of dnscrypt, if you have (juste like in the configuration of router) a static dns crypt, dnscrypt will still work... so you have to block the ip to forbid all form of unauthorized dns

**Comment by romaincointepas** [comment]
Use what's in RIPE, that's our anycast range. Some clients use direct unicast IPs, but we don't share those.

**Comment by quantumpacket** [comment]
@romaincointepas I checked my firewall logs and I've been having requests for DoT go to `194.62.167.148`, which according to RIPE belongs to [SMARTHOST](https://apps.db.ripe.net/db-web-ui/query?searchtext=194.62.167.148), but that domain resolves to `dns.nextdns.io`. The same thing happens with `209.208.110.56` which doesn't appear to be handled by RIPE [209.208.110.56](https://apps.db.ripe.net/db-web-ui/query?searchtext=209.208.110.56).

The current NextDNS RIPE record in above comments does not cover all the possible ranges. Firewall keeps blocking these unknown ranges and it would be nice to have a comprehensive list to allow for DoT. Thank you.
