### ISSUE TITLE
“NSABlocklist” dead list?

### ISSUE THREAD

**Issue by nitrohorse** [nextdns/metadata#408]
https://github.com/CHEF-KOCH/NSABlocklist 404s due to https://github.com/CHEF-KOCH not having an account on GitHub anymore. List was last updated 5 months ago.

**Comment by crssi** [comment]
Seems that the plagiarist CK was taken off again... go figure.

**Comment by scafroglia93** [comment]
+1 for remove this list

**Comment by beerisgood** [comment]
+1
Remove it

**Comment by Voltairine-de-Cleyre** [comment]
This is what I logged in for - to see if anyone yet reported this. Cool y'all have. Thank-you.

**Comment by romaincointepas** [comment]
Reached out to CHEF-KOCH to put this back online, we would rather not host it ourselves.

**Comment by Voltairine-de-Cleyre** [comment]
> Reached out to CHEF-KOCH to put this back online, we would rather not host it ourselves.

I'll host it if necessary, though it's not a list that will be updated (at least not very often) due to its nature. Back when Vault 7 was released, I helped Chef Koch gather all documents & information related to those documents, so I will also say that using a blocklist based (mostly) on the exploits described in the Vault 7 documents in hopes that it will work is, as they say, a fantasy. These are not tools that are used in mass surveillance like storing email correspondance & phone conversations. They are used in a targeted manner. So unless one is of enough importance to 1) get the attention of the CIA & become a person of interest & 2) spend the Hacking Team's time when they target you with tools ~5 years newer than those discussed in the Vault 7 documents. To summarize: I think the blocklist *may* help people avoid contacting Hacking Team hosted servers, it won't defend against actual targeted surveillance; however I will host it if enough people (more than 5) want me to.

**Comment by Voltairine-de-Cleyre** [comment]
Here's what I presume to be the final release of the file. It's licensed under the ISC license which is essentially as permissive as the MIT & BSD licenses. Being licensed this way in such a noticeable & public manner means I'll not be removing it until it's of no use to anyone.

- https://iosprivacy.com/random/HOSTS.txt
- https://cdn.rawgit.org/iosprivacy.com/random/HOSTS.txt
- https://gitlab.com/iosprivacy/cdn/raw/master/public/random/HOSTS.txt
