### ISSUE TITLE
Suggestion add a search option in Blocklist

### ISSUE THREAD

**Issue by Infamous-Jr** [nextdns/metadata#425]
Hello Dev, a suggestion it would be nice to see a search feature to serach for the filters in the add to Blocklist menu.

![IMG_20201005_083153](https://user-images.githubusercontent.com/68345385/95036530-e093eb80-06e5-11eb-862b-0dc757d56e34.jpg)

**Comment by Voltairine-de-Cleyre** [comment]
Interesting idea. Reminds me of a suggestion I wanted to make regarding TLD blocking.

**Comment by crssi** [comment]
Browser integrated CTRL+F comes to the rescue. ;)

**Comment by romaincointepas** [comment]
@Infamous-Jr Could you give me some example of what you would search for?

**Comment by Infamous-Jr** [comment]
> Browser integrated CTRL+F comes to the rescue. ;)

Yeah but I use my smartphone to acess the setup page. I known some browser has find in page features but I thought a inbuilt feature would be amazing.

**Comment by Infamous-Jr** [comment]
> @Infamous-Jr Could you give me some example of what you would search for?



> @Infamous-Jr Could you give me some example of what you would search for?

Since there are around 76 filters available and to find your fav filter you have to scroll all the way down and sometimes you might miss the filter you are searching for if you scroll fast.
For example I want to add Energized Blu which is in the situated in the middle of list now I have to scroll down carefully so that I don't skip it. But with the search feature I could type Energized & all the filters with the keywords Energized would be filtered and now I could add the filter without wasting time scrolling through the list.

**Comment by Voltairine-de-Cleyre** [comment]
Or simply keeping the list alphabetized would be of great help in such situations.  On Sat, Oct 17, 2020 at 10:03, Infamous-Jr <notifications@github.com> wrote:  

@Infamous-Jr Could you give me some example of what you would search for?


@Infamous-Jr Could you give me some example of what you would search for?

Since there are around 76 filters available and to find your fav filter you have to scroll all the way down and sometimes you might miss the filter you are searching for if you scroll fast.
For example I want to add Energized Blu which is in the situated in the middle of list now I have to scroll down carefully so that I don't skip it. But with the search feature I could type Energized & all the filters with the keywords Energized would be filtered and now I could add the filter without wasting time scrolling through the list.

**Comment by crssi** [comment]
It bothered me at first too that the list is not alphabetized, but the way it is, is simpler to see which lists have been added last.
Maybe not search as a search but as a filter?... when there is no some more important things to do.

**Comment by Voltairine-de-Cleyre** [comment]
That's an excellent point. I do enjoy scrolling to the bottom from time to time to see if/what's been added.On Sat, Oct 17, 2020 at 14:09, crssi <notifications@github.com> wrote:  
It bothered me at first too that the list is not alphabetized, but the way it is, is simpler to see which lists have been added last.
Maybe not search as a search but as a filter?... when there is no some more important things to do.

**Comment by Infamous-Jr** [comment]
Well it was just a suggestion if you guys don't think that it worth the hardwork then no problem You can close the issue. 
B/w Thank you for listening to my Suggestion.

**Comment by crssi** [comment]
Dont get me wrong, I think the idea is OK and also I am not a part of NextDNS team and its not on me at all.
I was just exploiting the free speech option. 😄

**Comment by romaincointepas** [comment]
Suggestion noted, thanks!

FYI, right now it's ordered by most used on NextDNS.
