### ISSUE TITLE
welcome2.wifi.id

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/metadata#455]
![image](https://user-images.githubusercontent.com/19517680/97877082-460fe200-1d4f-11eb-8418-bea4397b4c30.png)

welcome2.wifi.id

this domain for login (landing page from ISP Telkom Indonesia)

should be whitelist

**Comment by FarrelF** [comment]
Disclaimer: I'm not a NextDNS member

The address was blocked because that address resolves as Private/Local IP Addresses by DNS Rebinding Protection, so this is not related to any external/non-custom filter list.

And, you're using @wifi.id Network that needs login for activating Internet access and the landing page domain address needs to resolve as Private IP Addresses to do that. So, here is my solution:

- Add `wifi.id` domain to Allowlist from your NextDNS Account
- Or, you can disable "DNS Rebinding Protection" for Temporary until you're logged in
- Or, better you don't use NextDNS until you're logged in since there is not possible to resolve any domain (including `dns.nextdns.io` domain, except the landing page) if you are not logged in to your WiFi.

**Comment by romaincointepas** [comment]
@FarrelF is right, and unfortunately we can't exclude specific domains from that protection for security reasons.
