### ISSUE TITLE
Block EU cookie pop ups 

### ISSUE THREAD

**Issue by connorsmallman** [nextdns/metadata#462]
https://raw.githubusercontent.com/r4vi/block-the-eu-cookie-shit-list/master/filterlist.txt

**Comment by beerisgood** [comment]
First such a list doesn't work with DNS.

Second it's totally nonsense as if you don't config it, you may get all cookies which means even the one you can Opt-Out or Opt-In.
Third the configuration is only once per site as the choice is saved in their cookie.

Blocking privacy features like that just doesn't make sense.

**Comment by crssi** [comment]
Similar is already included in [oisd](https://oisd.nl/?p=inc) blocklist but, as @beerisgood is saying, it is useless (maybe a few lines that are not, not worth to include) on DNS level, since such must be dealt on a [HTML-DOM](https://www.w3schools.com/js/js_htmldom.asp) cosmetic level inside the browser to be effective.

Cheers

**Comment by connorsmallman** [comment]
Sorry my bad

**Comment by crssi** [comment]
Nothing to be sorry, really. 😉
