### ISSUE TITLE
$third-party modifier

### ISSUE THREAD

**Issue by skapytek** [nextdns/metadata#479]
Hello,
im using nextdns and the easylist and the adguard base filter and nextdns is blocking cdn.shortpixel.ai but its a false positive.
Website is a image cdn especially for wordpress.
AdguardTeam/AdguardFilters#66846 and easylist/easylist#6340 (comment)
I think you are interpreting the lists wrong.
shortpixel.ai^$popup shouldnt block cdn.shortpixel.ai

IMO nextdns should not include domains which have the $third-party modifier included.

For example entries on a list look like this:

cdn.shortpixel.ai$third-party

abcxyz.shortpixel.ai

Then nextdns should only block abcxyz.shortpixel.ai but not cdn.shortpixel.ai

**Comment by romaincointepas** [comment]
ADP-format blocklists mainly contain `$third-party` or `$popup`, because they can, and because there is no reason to not allow direct manual access to any website, doesn't matter how intrusive it is privacy-wise.

Pi-hole decided to NOT support the ABP format anymore. Our approach is to:
- support it, and include `$third-party` and `$popup` when extracting domains
- manually exclude false positives (as far as we know, those are still rare)
- add some sort of warning sign regarding this on my.nextdns.io (we should do this soon)

Can you share a page where the domain you mention is being called?

**Comment by skapytek** [comment]
Random domains which are affected:
adcash.com^$third-party
luxupcdna.com^$third-party
thiscdn.com^$third-party
pornkings.com^$third-party
pornattitude.com^$third-party
porngray.com^$third-party
xxxlive.com^$third-party
...
and so on

**Comment by romaincointepas** [comment]
Got it. Closing for now, feel free to open an issue with a list of domains to exclude from any specific list.

**Comment by krystian3w** [comment]
Broken Express VPN: https://github.com/AdguardTeam/AdguardFilters/issues/71720
