### ISSUE TITLE
Amazon Mobile App Blocked

### ISSUE THREAD

**Issue by josemarq** [nextdns/metadata#499]
I'm not sure exactly what is the domain blocked, but after this week the Amazon or Amazon Prime mobile apps are blocked.

Only I can see is:  fls-eu.amazon.fr, fls-eu.amazon.es, fls-eu.amazon.com appear blocked in the log, but even added this to the white list the problem remain from time to time. I have only active in Provacy the Nextdns recommended list. Only solution for now, is stop using Nextdns, buy in Amazon, and then re-enable next dns.

Anyone have an advice?.

Thanks in advance.
Regards, 
José

**Comment by timkgh** [comment]
Do you have Block Page enabled in your NextDNS configuration? That causes problems with mobile apps, not only Amazon.

**Comment by josemarq** [comment]
Thanks for reply. I will try that.

**Comment by Nisten-netizen** [comment]
> Do you have Block Page enabled in your NextDNS configuration? That causes problems with mobile apps, not only Amazon.
> I reported the issue a while back, not sure if NextDNS tried to fix it. I just stopped enabling Block Page in my configs.

Thanks for this info. For me, enabling the block page option actually breaks functionality of the Amazon Android mobile app, and the Wells Fargo Android mobile app. I hope they add this to the warning text under the Block Page subsection so people know ahead of time that enabling the block page has the potential to break mobile apps.

**Comment by romaincointepas** [comment]
If someone could help us figure out which domains should return 0.0.0.0 instead of the blockpage for those apps to not break, we would be very grateful.

**Comment by Nisten-netizen** [comment]
![Screenshot_20210104-104125](https://user-images.githubusercontent.com/76894165/103557878-707a3a80-4e79-11eb-827f-12d17c4c6ea1.png)

^ Domains used for Wells Fargo android mobile app

**Comment by romaincointepas** [comment]
@Nisten-netizen are you able to pinpoint the one(s) that breaks the app when the blockpage is returned? We don't want to disable the blockpage for domains that don't absolutely need it to be disabled.

**Comment by timkgh** [comment]
I tried at some point and it's hard to figure it out and I don't think it's feasible to do it for every mobile app that might break. My conclusion was that enabling the block page is a bad idea in general. Returning HTTP 200 with an HTML body when an app might expect json or something else is not great. Plus there are also the TLS certificate issues. It's not feasible to add it to all devices, on some you just can't (e.g. IoT devices).

One suggestion that may make things better: return 404 instead of 200, while still keeping the HTML body. That may help apps see the request as an error at least and hopefully deal with it better than seeing it as success and trying to parse the body as something that it isn't.

**Comment by Nisten-netizen** [comment]
![Screenshot_20210104-104706](https://user-images.githubusercontent.com/76894165/103558597-876d5c80-4e7a-11eb-9c1f-392cbb1ed559.png)

@romaincointepas Here are the domains that I personally encountered when using the Amazon android mobile app

**Comment by romaincointepas** [comment]
@timkgh TLS is usually the issue in those cases, not the status code/content-type/body (as far as we know). Not many apps break because of this, so our approach is to manually handle those few domains and respond with 0.0.0.0 instead.

**Comment by timkgh** [comment]
@Nisten-netizen I've been down this path with the Amazon apps. The problem is that these domains seem to change, they may depend on app updates or regions where you may be traveling to with your phone (CDN optimizations for example), sometimes there appear to be random/uuid-like subdomains, etc. It's a frustrating never ending battle, one minute the app works, the next it stops working because of a new subdomain.

**Comment by romaincointepas** [comment]
An approach to debugging this and figuring out the exact domains without having to selectively enable/disable the blockpage would be to:
1. list all domains blocked for that app.
2. whitelist one domain, wait 10 minutes, try the app again.
3. repeat 2. until the app suddenly works again, it means the last domain was causing the issue.

**Comment by Nisten-netizen** [comment]
@timkgh yeah that's why I ultimately ended up adding amazon as a top level whitelist for convenience before I found out that the root issue was enabling the block page. I also think it caused these sporadic errors using the Hulu roku app as I've had to occasionally re-whitelist hulu.hb-api.omtrdc.net

@romaincointepas I've initially tested this with the wells fargo android mobile app in 5 minute intervals as even disabling one of the whitelist entries displays a false negative "page/service is down or available" pop-up that prevents you from logging into the app

**Comment by Nisten-netizen** [comment]
I didn't test amazon for the same reason timgkgh referenced with the secondary/fallback/switchover domains

**Comment by pcmitsis** [comment]
@romaincointepas  For me allowing fls-eu.amazon.nl (Dutch Amazon) and then rewrite it to 0.0.0.0 worked fine. In general I think most domains of amazon fls-*.amazon.* should get to 0.0.0.0. Even better, as a future request an addition could be made next to denylist/allowlist to force redirect urls to 0.0.0.0 instead of the block page.

**Comment by pcmitsis** [comment]
Hi @romaincointepas ,
As an update here is the list with all amazon servers that shoud be redirected to 0.0.0.0:

fls-eu.amazon.ae
fls-na.amazon.ca
fls-cn.amazon.cn
fls-fe.amazon.co.jp
fls-eu.amazon.co.uk
fls-cn.amazon.com
fls-eu.amazon.com
fls-fe.amazon.com
fls-na.amazon.com
fls-fe.amazon.com.au
fls-na.amazon.com.br
fls-na.amazon.com.mx
fls-eu.amazon.de
fls-eu.amazon.es
fls-eu.amazon.fr
fls-eu.amazon.in
fls-eu.amazon.it
fls-eu.amazon.nl
fls-eu.amazon.sa
fls-eu.amazon.se
fls-fe.amazon.sg

**Comment by ben0a** [comment]
On my side, the blockpage is disabled since the beginning. The french CDNs for amazon are allowed (in fact the only one blacklisted is metrics). 
IOS app from Amazon is really clumsy to use. The scrolling is lagging to be almost unusable.

The only way to recover a smooth experience is by disabling NextDNS app or disabling it globally when on wifi.

using amazon.fr from safari is also really strange, with lot of images not loading.

I never had this experience previously when using pihole, a restriction on port 53 on my network and a million+ domains blocked.

**Comment by pcmitsis** [comment]
Hi all,
I was getting again issues in the amazon app. I checked the domain and it was aax-eu.amazon.nl which was a redirect from aax-eu-retail-direct.amazon-adsystem.com . Checking a bit in the StevenBlack host that is being used also by NextDns Ads & Trackers blocking list I found all the hosts:
![image](https://user-images.githubusercontent.com/8715672/144114205-0b7ce258-533a-4024-afdc-5a961bc2395d.png)

My solution:
**Allowlist:**
*.amazon-adsystem.com
**Rewrite:**
*.amazon-adsystem.com -> 0.0.0.0

**Comment by romaincointepas** [comment]
Fixed (forcing `0.0.0.0` for `amazon-adsystem.com`).
