### ISSUE TITLE
transmissionbt.com blocked by Piracy

### ISSUE THREAD

**Issue by timkgh** [nextdns/metadata#542]
That's the website for the Transmission client. It does not mean it has pirated content. I use it to download large Linux ISOs for example.

**Comment by Cybo1927** [comment]
Transmission is a BitTorrent client and the Piracy blacklist blocks torrent clients as they are often used to download and distribute pirated content. 

See https://github.com/nextdns/piracy-blocklists/blob/master/torrent-clients

**Comment by timkgh** [comment]
That doesn't sound right. By the same argument the list should block Chrome and Firefox too because they _can_ be used to search for and download pirated content.

Should kodi.tv be blocked too? Some people use Kodi to watch pirated content.

There is a big difference between sites that provide legitimate software which has many legitimate uses and sites that actually host pirated content.

**Comment by Cybo1927** [comment]
I would actually agree, though it's ultimately down to the NextDNS dev team. My comment was simply meant to state why it was blocked. I do believe it's just because it was originally meant for parental controls (hence why it's under that tab) and being able to use torrenting clients provides more of a way for kids to bypass parental controls.

And I feel I should mention I'm not a dev so this is my take on it :)

**Comment by romaincointepas** [comment]
The Parental Control -> Piracy category is not some sort of legal list on what we believe should exist or not on the Internet, it's a easy toggle to block websites or clients that are *mostly used* for piracy.

You can always allow specific domains with the Allowlist if needed.
