### ISSUE TITLE
*.lnks.gd not allowed by “allow affiliates and tracking links”

### ISSUE THREAD

**Issue by andschwa** [nextdns/metadata#622]
My county’s official newsletters use *.lnks.gd in their email newsletters, which are tracking links and so rightfully blocked by this list (and yes it’s annoying my government does this), but it should be allowed by the “allow affiliates and tracking links” option, yet it is not.

**Comment by crssi** [comment]
Which list does the denying?

**Comment by andschwa** [comment]
I'm not sure which sublist, but it was being reported denied by the NextDNS Ads & Trackers Blocklist.

**Comment by crssi** [comment]
It is part of @StevenBlack [list](https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts) and it came from Peter Lowe [list](https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext&useip=0.0.0.0).

You should contact @SteveBlack [here](https://github.com/StevenBlack/hosts/issues) and/or send an email to Peter Lowe at pgl@yoyo.org

Additionally, would you mind, please, share on of those links with us as an example?

Cheers

**Comment by beerisgood** [comment]
> It is part of @StevenBlack [list](https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts) and it came from Peter Lowe [list](https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext&useip=0.0.0.0).
> 
one more reason against his list as i already told many times.

**Comment by crssi** [comment]
So true... a lot of problems comes from there.

**Comment by andschwa** [comment]
Here is an example link: https://lnks.gd/l/eyJhbGciOiJIUzI1NiJ9.eyJidWxsZXRpbl9saW5rX2lkIjoxMDIsInVyaSI6ImJwMjpjbGljayIsImJ1bGxldGluX2lkIjoiMjAyMTAzMjYuMzc3NDM3MTEiLCJ1cmwiOiJodHRwczovL21lZGl1bS5jb20vd2FkZXB0aGVhbHRoL3ZhY2NpbmF0aW9uLWNhcmRzLWZmOTQ3Y2FiNjNjMCJ9.zPVSNjAAf9i6uA_d90ZIcd2ERzSSLufNDPz7VXvMGCc/s/742047117/br/100704426654-l

**Comment by andschwa** [comment]
Oh and this is King County in Washington State, USA, not Grenada 😅

**Comment by crssi** [comment]
I have sent email to Peter Lowe.
But I think the agility of StevenBlack lists should be responsibility of @StevenBlack or @romaincointepas should really rethink which lists should be NextDNS default.

I would suggest you to use 1Hosts Lite and OISD together instead of NextDNS default. 
Both maintainers (@badmojr and Stephan) are extremely fast in resolving the problems, mostly counting in hours instead of waiting for months and sometimes loosing time with useless arguing's and on the end it never happens. Kudos to both of them.

That is quite frustrating and I for sure understand @scafroglia93 frustration the other day.

I hope I don't get banned for saying out loud, but criticism is sometimes really needed to try to make things even better.

Cheers

**Comment by crssi** [comment]
I have got an answer from Peter (thank you for the fast answer).

But this is what I am talking about,.. here is the answer... judge it by yourself:
```
Hi,

It doesn't matter who uses the domain, it's still a tracker.

My list includes trackers.

If this is inconvenient for you and you don't mind your user behaviour
being tracked, then you can either allow trackers, or just this domain,
or not use my list.

cheers,

 - Peter
 ```

I really think that @romaincointepas should rethink the default selection ASAP.

Cheers

**Comment by beerisgood** [comment]
Hard to see such a response from a known list maintainer.
Looks like he doesn't care about user/ web experience at all.

In my opinion such lists should be avoided at all cost. NextDNS user doesn't want such problems.
@nextdns

**Comment by StevenBlack** [comment]
@beerisgood do you know what curation means?

Peter Lowe @pgl cares deeply about the quality of his list.

He cares far less about the unsubstantiated opinions of random eggs on the Internet.

Let's see if you can do what you do without ascribing motives to dedicated non-anonymous people who have been doing this for a long time.

**Comment by pgl** [comment]
Hi there. Thanks for the ping, @StevenBlack.

I'm sorry for the blunt reply to your email, but I felt your email justified it.

You wrote:

> You have listed domain lnks.gd, but it seems important and should not be listed.
> 
> The important US government news/notices are send over email using this domain.
> US Coast Guard (US Department of Homeland Security) and Washington State Department of Health are among them.
> 
> The link is used only when user really opens it.

None of these reasons stop the domain being a tracker. When you click the link, it goes through this domain specifically so it can record data about you and your behaviour. (Probably more information than you might realise, as well.) Then you get redirected to the target URL. This means it's a tracker.

My list includes trackers; that's one of the main things I have on the list, along with ad servers. If you're fine with tracking -- if you value your "user / web experience" above your user behaviour being tracked -- then just disable my list, or add the trackers to your personal allow list.

There's always two sides to this - people who want better blocking, and people who want better user experience. People blocking all trackers and ad servers aren't going to have as good an experience as people who do, because sites and organisations tie functionality to tracking services. It's a shitty situation and honestly frustrates me, but that's how it works.

Or, if you really want to fix this situation, contact the people who are unnecessarily tracking clicks from their newsletters. The US government and the US Coast Guard don't really need to be doing that. Send them pissy emails complaining about pointless tracking that's breaks functionality when it's blocked.

**Comment by crssi** [comment]
@pgl and others

Don't get me wrong. I do respect Peter's choice... at the end this is his list and his work and I do support his answer fully.

This has actually nothing to do with @pgl and his list, but it has a lot to do to the @nextdns choice of default lists and the agility to resolve the opened issues very fast, since it make users suffer otherwise.

Or those lists needs to be maintained so that users do no suffer from breakages or it should be changed for more appropriate list/source..

You can see yourself at this repository issues that most problems/breakages are cumming exactly from the same source.

I don't have those problems due to avoiding using lists that causes a breakages, since "my users" do no buy any excuse for breakages.
That does not mean those lists (of my choice) never causes the problems, but those maintainers are responding promptly to any issue.

And let me say once again 2 very important things:
1. Kudos to all maintainers that are hard working for all of us, that includes @pgl without any doubt. Thank you.
2. End users doesn't give a f... for any excuse why something doesn't work if they need it to work... the only exception is security.

Cheers and ❤️

**Comment by scafroglia93** [comment]
I break a lance in favor of @StevenBlack since the cdn.iubenda.com block (it is one of the few that blocks it) is a godsend for removing the annoying banner that appears on any site

**Comment by StevenBlack** [comment]
Lorenzo @scafroglia93 the `cdn.iubenda.com` comes to us via [AdAway](https://adaway.org/).

**Comment by scafroglia93** [comment]
I believe that nextdns shouldn't have preferences on lists; people must be free to develop their own blocklist according to their knowledge and priorities

Let's say that many do not have clear ideas because, preferring a list like 1hosts is somewhat complicated since no information is provided about the upstream source but not for nothing it is the daughter of energized

Maybe it takes some time, the resolution is not lightning fast but, for this there is a function called whitelist that allows you to bypass the block temporarily

**Comment by badmojr** [comment]
> I believe that nextdns shouldn't have preferences on lists; people must be free to develop their own blocklist according to their knowledge and priorities
> 
> Let's say that many do not have clear ideas because, preferring a list like 1hosts is somewhat complicated since no information is provided about the upstream source but not for nothing **it is the daughter of energized**
> 

Proof?

> Maybe it takes some time, the resolution is not lightning fast but, for this there is a function called whitelist that allows you to bypass the block temporarily
> 
> PS ->
> for myself, a list that uses other lists and **does not show the sources used should be removed**; he's a piece of shit towards other maintainers

Hahaah! https://github.com/badmojr/1Hosts/issues/106

> [badmojr/1Hosts@a6f8e02](https://github.com/badmojr/1Hosts/commit/a6f8e020e051fa58e43a90817f218587b2be452f)
> (that's 1hosts script based list)
> @romaincointepas

**Comment by scafroglia93** [comment]
Proof ->
The management is almost identical, certainly the quality of a list is not measured on the basis of the unblocking requests that are made

If I were to have only 1hosts I would definitely go to quad9

PS ->
Why don't you publish the lists you use within yet another energized child script?

**Comment by badmojr** [comment]
> Proof ->
> The management is **almost identical**, certainly the quality of a list is not measured on the basis of the unblocking requests that are made
> 

How  identical?

> If I were to have only 1hosts I would definitely go to quad9
> 
Your point being?

> PS ->
> Why don't you publish the lists you use within yet another **energized child script?**

The hell you talking about?

**Comment by scafroglia93** [comment]
> 
> 
> > Proof ->
> > The management is **almost identical**, certainly the quality of a list is not measured on the basis of the unblocking requests that are made
> 
> How identical?
> 
> > If I were to have only 1hosts I would definitely go to quad9
> 
> Your point being?
> 
> > PS ->
> > Why don't you publish the lists you use within yet another **energized child script?**
> 
> The hell you talking about?

This ->
https://github.com/badmojr/1Hosts/blob/master/statics/assets.txt

That's insane

**Comment by badmojr** [comment]
o-k!

**Comment by andschwa** [comment]
What on earth happened here...

**Comment by blaineclrk** [comment]
Over a year later;
This messes with HHS.gov and CMS.gov in the US such as on this link;
https://lnks.gd/l/eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImJsYWluZWNscmtAZ21haWwuY29tIiwiYnVsbGV0aW5fbGlua19pZCI6IjExNSIsInN1YnNjcmliZXJfaWQiOiIyOTE5Njg5MDA4IiwibGlua19pZCI6IjI1Mzc5NDYwMDMiLCJ1cmkiOiJicDI6ZGlnZXN0IiwidXJsIjoiaHR0cHM6Ly93d3cuY21zLmdvdi9vdXRyZWFjaC1hbmQtZWR1Y2F0aW9ub3V0cmVhY2hmZnNwcm92cGFydHByb2dwcm92aWRlci1wYXJ0bmVyc2hpcC1lbWFpbC1hcmNoaXZlLzIwMjItMTEtMjMtbWxuYyIsImJ1bGxldGluX2lkIjoiMjAyMjExMjMuNjcxMzUwNzEifQ.UZtSfQ68HkJOww883NdNgtTSj0bPjzGxvaFDUGO-XQA
It is a PITA (Pain In The Asterix), but really, why would any government agencies need such tracking? As a work around I can usually copy the article title, do a web search and find it, bypassing the tracking issue. This doesn't always work, but usually it does. I'll abide with the inclusion of blocking lnks.gd and continue to use the available block lists that include this tracker.
BTW, I'm on Debian 11 with paranoid level privacy. I have PortMaster and Privoxy installed, along with system installations of (webext)Privacy Badger and (webext)Ublock. I get zero ads, zero tracking and minimal fingerprinting which means I should be an enigma to those eavesdropping. When I log into any Google service or Facebook I get immediate "OMG! Who are you? We don't recognize you! You need to adjust your security!" emails from them. Knowing I'm screwing with them makes a few inconveniences so worth it.
