### ISSUE TITLE
False Positive - r20.rs6.net

### ISSUE THREAD

**Issue by wcrahen** [nextdns/metadata#638]
The domain r20.rs6.net is being blocked by the NextDNS Ads and Trackers Blocklist.

**Comment by Cybo1927** [comment]
Could you please elaborate? What exactly is broken with this blocked?

**Comment by wcrahen** [comment]
Not sure it's broken, but this was false positive (legit domain being blocked by that list), adding it to an allow list resolved the issue. Is this were False Positives should be posted, or is there a different place to submit those? Thanks.

**Comment by Cybo1927** [comment]
> Not sure it's broken, but this was false positive (legit domain being blocked by that list), adding it to an allow list resolved the issue.

So what exactly was the issue? I understand it's a legit domain but calling it a false positive brings the connotation that something was broken or not working due to it being blocked. So, I guess what I'm asking is what makes this worthy of being whitelisted and what's it used for?

> Is this were False Positives should be posted, or is there a different place to submit those?

As far as I know this is the right place to post issues. But I'm not a dev, I just try and help resolve issues because the maintainer seems to be fairly inactive and I like the project.

Thanks for the quick response though :)

**Comment by wcrahen** [comment]
That domain is owned by Constant Contact and it is a very popular service for newsletters and such, just looking through my email and I have about 6 legit services using Constant Contact, which is how I noticed that it was being blocked.

**Comment by Cybo1927** [comment]
Thanks! This info is usually what's needed to know if an entire domain or just the subdomain should be unblocked which is why I asked. 

Hope this issue gets resolved soon!

**Comment by romaincointepas** [comment]
Already included in the Allow Affiliate & Tracking Links feature.
