### ISSUE TITLE
Adblock Warning Removal List

### ISSUE THREAD

**Issue by mikedelic** [nextdns/metadata#683]
Please add the following blocklist.

https://easylist-downloads.adblockplus.org/antiadblockfilters.txt

**Comment by quantumpacket** [comment]
Those do not work with DNS.

**Comment by mikedelic** [comment]
What does work with DNS?

**Comment by beerisgood** [comment]
> What does work with DNS?
> 

Domains like github.com.
You should read about DNS

**Comment by mikedelic** [comment]
Would this work?
https://github.com/reek/anti-adblock-killer#anti-adblock-killer--reek

**Comment by quantumpacket** [comment]
No. Just throwing list suggestions without knowing how DNS works is not productive.

**Comment by beerisgood** [comment]
Please close this issue as it doesn't make sense nor can be solved.

**Comment by mikedelic** [comment]
You’re right. You’re the experts. What would be productive is to know if there are any potential plans on the table to add anti-adblock to your NextDNS Filters for paid customers, instead of short rude comments. FYI: This is where customers are routed to make these types of suggestions. https://help.nextdns.io/t/q6hmva4/custom-blocklist-support

**Comment by crssi** [comment]
Did search for some nicely written article explaining difference between DNS and path or content filtering.
I am not good at explaining, but since I haven't found any good article, I will try...

Filtering on DNS level works only for hosts, that is:
you can control to allow or deny DNS requests on host level like for example `subdomain.example.net`
but you can't go deeper into to allow or deny by URL path for example subdomain.example.net`/somepath/etcetera`, since DNS does not know nothing about the path
also you cant control on DNS level the behavior on content level

So, for path or content level you need in-browser solution like uBlock Origin or similar.

Think of DNS as of a telephone book.
So you can control the telephone numbers, but not extensions (like URL path), and you cant control by the words spoken over the line.

Cheers

**Comment by romaincointepas** [comment]
As said in this thread, those lists unfortunately do not work at the DNS level.

Great explanation @crssi by the way.
