### ISSUE TITLE
plz unblock episub.com

### ISSUE THREAD

**Issue by MgrOnDuty** [nextdns/metadata#724]
Hi,
Please unblock our domain https://www.episub.com

Thanks.

**Comment by crssi** [comment]
Your domain is on `Threat Intelligence Feeds` due to `http://episub.com/wp-content/plugins/zkhucld/remittance1111.jar` listed in `https://urlhaus.abuse.ch/downloads/text`.

I guess you need to take better care of your domains content.
To get off the list contact `https://urlhaus.abuse.ch/` and do a cleanup on your side.

Cheers
