### ISSUE TITLE
Suspicious site in my logs "en.free-wallpapers.su"

### ISSUE THREAD

**Issue by Rexadev** [nextdns/metadata#851]
`en.free-wallpapers.su`

**Comment by fdhfgbsjedfg-775** [comment]
I don't think it is a malicious domain, since I had it go through metadefender.opswat.com, virustotal.com, urlscan.io, urlvoid.com and sitecheck.sucuri.net and even [1Hosts Xtra](https://raw.githubusercontent.com/badmojr/1Hosts/master/Xtra/domains.txt), yet no red flags, I even tried downloading a cat wallpaper, checked the extension incase its a .exe or some other non image extension, conclusion was a .jpg extension. I can understand why you may be worried that this domain is malicious since its AS and ASN is based in Russia, but there are thousands of other domains based in China, India, USA and some other countries that outnumber Russia fiftyfold. It's safe to say the total conclusion is that, its a safe domain, anyone can use it safely, if there are some other spyware domains hiding in the now considered safe domain or other things, let me know.
