### ISSUE TITLE
Xiaomi MIUI ROM updates blocked

### ISSUE THREAD

**Issue by radupotop** [nextdns/metadata#892]
I noticed that Xiaomi MIUI ROM updates are being blocked. The requests lead to the following domain:

```
rom.miui.com
```

Putting that domain on the Allowlist fixes it.

**Comment by radupotop** [comment]
The only blocklists I'm using are: "NextDNS Ads & Trackers Blocklist" and "AdGuard DNS filter"; with "Block Disguised Third-Party Trackers" set to ON, "Allow Affiliate & Tracking Links" set to ON.

**Comment by crssi** [comment]
Are you sure?
Since here without any protection the `nslookup rom.miui.com` doesn't resolve to anything.
Also there are no resolving at all for A,CNAME and AAAA... see:
`https://dnschecker.org/#A/rom.miui.com`
`https://dnschecker.org/#AAAA/rom.miui.com`
`https://dnschecker.org/#CNAME/rom.miui.com`

Something must be off here.

**Comment by radupotop** [comment]
Yes you're right, so the exact subdomain is `connect.rom.miui.com` 

I just allowed rom.miui.com for some reason.

**Comment by crssi** [comment]
To avoid breakages you could try "my config" that you can find on my github repository. 😉

**Comment by Rexadev** [comment]
Whitelist these 
Allowlist System App
global.market.xiaomi.com
Allowlist ROM Update
*.api.io.mi.com
*.update.intl.miui.com
*.update.miui.com

**Comment by romaincointepas** [comment]
Seems fixed
