### ISSUE TITLE
Filtering category missing 

### ISSUE THREAD

**Issue by SohanRay** [nextdns/metadata#921]
In the parental control section, in the categories, why isn't there a category of drugs?

**Comment by quantumpacket** [comment]
I presume it would be difficult to determine what is considered a drug based on local laws, culture, etc. A similar argument can be made for alcoholic websites as the minimum age varies across countries.

I'd make a stronger argument as to why there is no blocking for sites that promote/serve content for  _Self-Harm_, and _Gore_.

**Comment by SohanRay** [comment]
Well drugs should be the ones that has no medicinal purpose anywhere and is considered illegal in almost all countries. 
In addition, Your opinion on blocking sites promoting  self-harm etc is also valid.

**Comment by quantumpacket** [comment]
> Well drugs should be the ones that has no medicinal purpose anywhere and is considered illegal in almost all countries.

In that case, CBD which you can buy at the gas station in the U.S. (depending on which state you are in, some with no age limit) is illegal in almost every country. The U.S. federal government says it has no medicinal value, but individual states have argued otherwise.

A drug category can become very political on what is allowed or not. For that reason alone I would be against it.
