### ISSUE TITLE
False positive:  wl.spotify.com in NextDNS Ads & Trackers Blocklist

### ISSUE THREAD

**Issue by Sduibek** [nextdns/metadata#988]
This subdomain is used for legitimate purposes with links in Spotify emails, for example when selecting "unsubscribe" or "edit my profile".

The text usually appears something like-

_"This message was sent to [emailaddress]. If you don't want to receive these emails from Spotify in the future, you can **edit your profile** or **unsubscribe**."_

**Comment by quantumpacket** [comment]
They are likely click-tracking links, which a lot of companies use in their emails. This would not be considered a false positive, because to protect from tracking such links should be blocked.

**Comment by Sduibek** [comment]
What's the typical advice then besides temporarily whitelisting the given (sub)domain? 

I get that if we currently have an account we can just log in manually instead of using their link in the email, but I've run into a bunch of situations with various sites and companies where that's not possible and the only way to unsubscribe is through the email link.

**Comment by quantumpacket** [comment]
> I get that if we currently have an account we're able to log in to we can just log in manually instead of using their link in the email,

That's what I would do. It also has an added benefit of helping prevent potential phishing attacks, since you manually visit your account login opposed to trusting that the URL in the email is safe.

> but I've run into a bunch of situations with various sites and companies where that's not possible and the only way to unsubscribe is through the email link.

Some subscription emails will contain a `List-Unsubscribe` email header, which will contain an unsubscribe link and/or a unsubscribe email. This may or may not be link tracked.

Sometimes it's just better to just blacklist the sender email, opposed to unsubscribing as it prevents them from knowing your email account is actively in use, which could result in further emails from them or the sale of your email address to other 3rd parties.

**Comment by Sduibek** [comment]
Thanks so much! Appreciate the info as well. 😊
