### ISSUE TITLE
False positive: privaterecords.net by AI-Driven Threat Detection

### ISSUE THREAD

**Issue by Sduibek** [nextdns/metadata#989]
Data brokers and people-search sites are a gross and deeply concerning industry, but if we want to get our info removed from these sites/databases (and everyone should!), it's necessary to visit the site to do so - and we can't if a filter is blocking the entire site categorically.

**Comment by quantumpacket** [comment]
No offense, but you'd have to be pretty naive to think such sites' opt-out features are legit. Just look at the information they **require** for you to remove a record.

![Screenshot_2022-05-23_12-36-01](https://user-images.githubusercontent.com/8516784/169866859-86a4a656-4fa0-4bac-9fec-6b3c2df82654.png)

Not only are you providing your information (which may differ from their records), but you are also verifying which records are inaccurate along with providing a verified email address. Exactly what they need to make your personal information more profitable than others.

The best way to stop these record companies, is to limit what information you give out online and in real life. Public records on the other hand, are public and no amount of opting out will remove them.

This is not a false positive, because we would not want people to fall for this trickery and inadvertently give out their information.

**Comment by Sduibek** [comment]
Thanks for taking a look, I do truly appreciate that. Wasn't expecting the snark and condescension though. Do you typically reply this way to people who are trying to help? It's weird that you assume by default that i have no idea what I'm talking about.

As for them requiring info to remove info, that is sadly and disappointingly very common amongst these companies/sites. But the opt-out process itself is indeed legit for every site I've submitted to, which is about 200 at this time. This is especially true now that we have things like CCPA that at least hold these companies somewhat accountable. All of this can - "no offense" - be confirmed via various impartial 3rd parties with a couple brief web searches. No need to take my word for it. 

You are correct that a proactive limiting of what one shares is the most effective way to go (in addition to a VPN and/or blockers like yours), but it's far oversimplified as singular advice - and also incorrect to imply that that means there's no value in taking actions to retroactively limit the ease of availability of what's currently out there. Also very unrealistic as singular advice considering how many people have spent years and decades with no idea the importance of limited sharing to begin with - so the manual clearing is of great value to them to "start fresh" as much as is possible.

It's fair to assume I don't like these bottom-feeders any more than you do, but blocking one or two among 500+ doesn't really do anyone any favors, and as originally mentioned will likely in fact prevent them from getting their info removed from the site(s).

**Comment by romaincointepas** [comment]
We will investigate this, thanks.
